FROM node:18-alpine

WORKDIR /app

COPY package.json .

# Install dependencies
RUN npm install

COPY . .

# Expose port for Vite
EXPOSE 5173

# Start development server
CMD ["npm", "run", "dev", "--", "--host"]
